//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesDisponibilidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa_tb
    {
        public int idEmpresa { get; set; }
        public string NomeEmpresa { get; set; }
        public string Endereco { get; set; }
        public string Nuit { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public byte[] LogoTipo { get; set; }
    }
}
