//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesDisponibilidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaViatura_tb
    {
        public int idEntrada { get; set; }
        public Nullable<System.DateTime> DataRegistro { get; set; }
        public Nullable<int> RegistradoPor { get; set; }
        public Nullable<int> idSaida { get; set; }
        public Nullable<int> ActualizadoPor { get; set; }
    
        public virtual SaidaViatura_tb SaidaViatura_tb { get; set; }
    }
}
