//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesDisponibilidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class FluidosManutencao_tb
    {
        public int idFluidoManutencao { get; set; }
        public Nullable<int> idFluido { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<int> idManutencao { get; set; }
    
        public virtual Fluidos_tb Fluidos_tb { get; set; }
        public virtual Manutencao_tb Manutencao_tb { get; set; }
    }
}
