//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesDisponibilidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manutencao_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manutencao_tb()
        {
            this.FluidosManutencao_tb = new HashSet<FluidosManutencao_tb>();
            this.PecasManutencao_tb = new HashSet<PecasManutencao_tb>();
        }
    
        public int idManutencao { get; set; }
        public Nullable<int> idVeiculo { get; set; }
        public Nullable<int> idServico { get; set; }
        public string TipoManutencao { get; set; }
        public Nullable<System.DateTime> DataRegisto { get; set; }
        public Nullable<System.DateTime> DataManutencao { get; set; }
        public string KilometragemManutencao { get; set; }
        public Nullable<decimal> ValorManutencao { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFim { get; set; }
        public string NivelTanque { get; set; }
        public string Observacoes { get; set; }
        public Nullable<int> idCliente { get; set; }
    
        public virtual Cliente_tb Cliente_tb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FluidosManutencao_tb> FluidosManutencao_tb { get; set; }
        public virtual Servicos_tb Servicos_tb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PecasManutencao_tb> PecasManutencao_tb { get; set; }
    }
}
