//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesDisponibilidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca_tb()
        {
            this.Viatura_tb = new HashSet<Viatura_tb>();
        }
    
        public int idMarca { get; set; }
        public string NomeMarca { get; set; }
        public Nullable<System.DateTime> DataRegistro { get; set; }
        public Nullable<int> RegistradoPor { get; set; }
        public Nullable<int> ActualizadoPor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viatura_tb> Viatura_tb { get; set; }
    }
}
