//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesDisponibilidade
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GesviaturasEntities : DbContext
    {
        public GesviaturasEntities()
            : base("name=GesviaturasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente_tb> Cliente_tb { get; set; }
        public virtual DbSet<Empresa_tb> Empresa_tb { get; set; }
        public virtual DbSet<EntradaViatura_tb> EntradaViatura_tb { get; set; }
        public virtual DbSet<Fluidos_tb> Fluidos_tb { get; set; }
        public virtual DbSet<FluidosManutencao_tb> FluidosManutencao_tb { get; set; }
        public virtual DbSet<Manutencao_tb> Manutencao_tb { get; set; }
        public virtual DbSet<Marca_tb> Marca_tb { get; set; }
        public virtual DbSet<PecasManutencao_tb> PecasManutencao_tb { get; set; }
        public virtual DbSet<SaidaViatura_tb> SaidaViatura_tb { get; set; }
        public virtual DbSet<Servicos_tb> Servicos_tb { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario_tb> Usuario_tb { get; set; }
        public virtual DbSet<Viatura_tb> Viatura_tb { get; set; }
        public virtual DbSet<View_CarroMarca> View_CarroMarca { get; set; }
        public virtual DbSet<View_Saida> View_Saida { get; set; }
        public virtual DbSet<Abastecimento_tb> Abastecimento_tb { get; set; }
        public virtual DbSet<View_Manutencao> View_Manutencao { get; set; }
        public virtual DbSet<View_FluidosManutencao> View_FluidosManutencao { get; set; }
        public virtual DbSet<View_Abastecimento> View_Abastecimento { get; set; }
    }
}
