//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesDisponibilidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaidaViatura_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaidaViatura_tb()
        {
            this.EntradaViatura_tb = new HashSet<EntradaViatura_tb>();
        }
    
        public int idSaida { get; set; }
        public Nullable<System.DateTime> DataSaida { get; set; }
        public Nullable<System.DateTime> DataDevolucao { get; set; }
        public Nullable<System.DateTime> DataRegistro { get; set; }
        public Nullable<int> RegistradoPor { get; set; }
        public Nullable<int> ActualizadoPor { get; set; }
        public Nullable<int> Diasdealerta { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idViatura { get; set; }
    
        public virtual Cliente_tb Cliente_tb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntradaViatura_tb> EntradaViatura_tb { get; set; }
        public virtual Viatura_tb Viatura_tb { get; set; }
    }
}
