//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesDisponibilidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Manutencao
    {
        public int idServicos { get; set; }
        public string NomeServico { get; set; }
        public int idManutencao { get; set; }
        public Nullable<int> idVeiculo { get; set; }
        public string TipoManutencao { get; set; }
        public Nullable<System.DateTime> DataRegisto { get; set; }
        public Nullable<System.DateTime> DataManutencao { get; set; }
        public string KilometragemManutencao { get; set; }
        public Nullable<decimal> ValorManutencao { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFim { get; set; }
        public string NivelTanque { get; set; }
        public string Observacoes { get; set; }
        public int idCliente { get; set; }
        public string NomeCliente { get; set; }
    }
}
