//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesDisponibilidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_FluidosManutencao
    {
        public string NomeFluido { get; set; }
        public string UnidadeMedida { get; set; }
        public int idFluidoManutencao { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<int> idManutencao { get; set; }
        public int idFluido { get; set; }
    }
}
